### ISSUE TITLE
ライセンスつーけて

### ISSUE THREAD

**Issue by exice** [Asyley/OpenCoronaVacation#9]
[5. 他のユーザへのライセンス許可](https://docs.github.com/ja/site-policy/github-terms/github-terms-of-service#5-%E4%BB%96%E3%81%AE%E3%83%A6%E3%83%BC%E3%82%B6%E3%81%B8%E3%81%AE%E3%83%A9%E3%82%A4%E3%82%BB%E3%83%B3%E3%82%B9%E8%A8%B1%E5%8F%AF)
Issue、コメント、他の「ユーザ」のリポジトリへのコントリビューションなど、お客様が公に投稿する「ユーザ生成コンテンツ」は、他者によって閲覧される場合があります。 リポジトリを公に表示するように設定することにより、お客様は、他者がリポジトリを表示および「フォーク」できるようになることに同意するものとします (これは、他者が管理するリポジトリ内のお客様のリポジトリから他者が「コンテンツ」の独自の複製を作成できることを意味します)。

お客様が自身のページおよびリポジトリを公に表示するように設定した場合、お客様は GitHub の「サービス」を通じて「あなたのコンテンツ」を使用、表示、および実演し、また GitHub の機能を通じて許可される限りにおいて (フォークなど) のみ GitHub 上で「あなたのコンテンツ」を複製する、非独占的かつ世界的ライセンスを GitHub の各「ユーザ」に付与します。 お客様が[ライセンスを採用](https://docs.github.com/ja/articles/adding-a-license-to-a-repository/#including-an-open-source-license-in-your-repository)した場合、他の権利を付与することができます。 お客様が作成または所有していない「コンテンツ」をアップロードする場合には、アップロードする「コンテンツ」が、これらの権限を GitHub の他の「ユーザ」に付与する条項に基づいて必ずライセンスされるよう図る責任を負います。

**Comment by Asyley** [comment]
取り急ぎMITライセンスをつけた

**Comment by exice** [comment]
たすかる
